version: "3"
services:
  mongo:
    image: mongo:5.0.2
    ports:
      - "127.0.0.1:27017:27017"
    command: [ --replSet, rs0 ]
    volumes:
      - mongodb_data:/data/db:rw
      - ./docker/01-replica-set.init.js:/docker-entrypoint-initdb.d/01-replica-set.init.js
      - ./docker/02-collections.init.js:/docker-entrypoint-initdb.d/02-collections.init.js
    networks:
      - articles

volumes:
  mongodb_data:

networks:
  articles:
