server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    path: /error

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: articles
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE

anonymous-allowed: false
default-realm: default
default-userid: anonymous
realm-header: X-Auth-Realm
userid-header: X-Auth-Userid
username-header: X-Auth-Username
